# Changable configurations
tss.contract.max-hours-per-week=20
tss.contract.default-working-days-per-week=5
tss.contract.default-vacation-days-per-year=20
tss.contract.default-archive-duration-months=24

tss.holiday.default-state=RHINELAND_PALATINATE
tss.holiday.min-year=2025
tss.holiday.max-year=2030

tss.timezone=Europe/Berlin

tss.reminder.sender-email=noreply@sierra-tss.example
tss.reminder.email-subject=TSS: You have pending timesheet reminders
tss.reminder.message-bundle=sierra.tms.i18n.reminder_messages
