package sierra.tms.web;

public enum ApplicationFeature {
    VIEW_CONTRACT,
    VIEW_TIMESHEETS,
    REPORT_WORK,
    SIGN_TIMESHEET,
    COUNTERSIGN_TIMESHEET,
    REQUEST_TIMESHEET_CHANGES,
    VIEW_STATISTICS,
    MANAGE_CONTRACT,
    CREATE_CONTRACT,
    START_CONTRACT,
    TERMINATE_CONTRACT,
    PRINT_CONTRACT,
    PRINT_TIMESHEET,
    ARCHIVE_TIMESHEET,
    SYSTEM_OVERVIEW,
    SEARCH_RECORDS,
    MANAGE_PEOPLE,
    REVOKE_SIGNATURE
}
