package sierra.tms.utils.enums;

public enum States {
    RHINELAND_PALATINATE,
    BADEN_WUERTTEMBERG,
    BAVARIA,
    BERLIN,
    BRANDENBURG,
    BREMEN,
    HAMBURG,
    HESSE,
    MECKLENBURG_VORPOMMERN,
    LOWER_SAXONY,
    NORTH_RHINE_WESTPHALIA,
    SAARLAND,
    SAXONY,
    SAXONY_ANHALT,
    SCHLESWIG_HOLSTEIN,
    THURINGIA
}
